variable "subscription_id" {}
variable "tenant_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "object_id" {}
variable "location" {}
variable "ssh_public_key" {}
variable "resource_group_name" {}
variable "quickops_admin_username" {}
